[package]
name = "rb-sys-tests"
version = "0.9.13"
edition = "2018"
autotests = false
publish = false

[dependencies]
rb-sys = { path = "../rb-sys", default-features = false, features = ["link-ruby", "ruby-macros"] } 
ctor = "0.1"

[[test]]
name = "rb-sys-tests"
path = "tests/lib.rs"
harness = true