---
name: 🍽 Setup boilerplate
inputs:
  os:
    required: true
    description: Operating system
  ruby_version:
    required: true
    description: Ruby version
  rust_toolchain:
    required: true
    description: Rust toolchain
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      if: inputs.ruby_version != 'skip'
      with:
        ruby-version: ${{ inputs.ruby_version }}
        bundler-cache: true
    - name: Bundle install
      if: inputs.ruby_version == 'skip'
      shell: bash
      run: bundle install -j3
    - name: 🐛 Print debug info
      run: ruby -rrbconfig -ryaml -e 'puts RbConfig::CONFIG.to_yaml'
      shell: bash
    - name: ⚡ Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          examples/rust_reverse/tmp/
        key: ${{ inputs.os }}-${{ inputs.ruby_version }}-${{ inputs.rust_toolchain }}-cargo-v4-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.rust_toolchain }}
        default: true
    - name: Fix clang dep for rust-bindgen (see https://github.com/rubygems/rubygems/pull/5175#discussion_r794873977)
      if: ${{ contains(inputs.os, 'windows') }}
      shell: bash
      run: |
        if [ -n "$MINGW_PACKAGE_PREFIX" ]; then
          pacman --remove --cascade --noconfirm mingw-w64-x86_64-clang
          pacman --sync --noconfirm --needed $MINGW_PACKAGE_PREFIX-clang 
        else
          pacman --remove --cascade --noconfirm mingw-w64-x86_64-clang
          pacman --sync --noconfirm --needed mingw-w64-x86_64-gnu
        fi
