[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/oxidize-rb/x86_64-linux:3.2-ubuntu"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/oxidize-rb/aarch64-linux:3.2-ubuntu"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/oxidize-rb/aarch64-linux-musl:3.2-ubuntu"
