[package]
name = "rb-sys-build"
version = "0.9.13"
edition = "2018"
description = "Build system for rb-sys"
homepage = "https://github.com/oxidize-rb/rb-sys"
license = "MIT OR Apache-2.0"
repository = "https://github.com/oxidize-rb/rb-sys"

[dependencies]
regex = "1" 