# Ensure this version matches the rack-compiler-version in Gemfile
FROM ghcr.io/rake-compiler/rake-compiler-dock-image:1.12.0-mri-arm-linux-musl

ENV RUBY_TARGET="arm-linux-musl" \
    RUST_TARGET="arm-unknown-linux-musleabihf" \
    RUSTUP_DEFAULT_TOOLCHAIN="stable" \
    RUSTUP_HOME="/usr/local/rustup" \
    CARGO_HOME="/usr/local/cargo" \
    CARGO_BUILD_TARGET="arm-unknown-linux-musleabihf" \
    CARGO_TARGET_ARM_UNKNOWN_LINUX_MUSLEABIHF_RUSTFLAGS="-C target-feature=-crt-static" \
    CARGO_TARGET_ARM_UNKNOWN_LINUX_MUSLEABIHF_LINKER="arm-linux-musleabihf-gcc" \
    PKG_CONFIG_ALLOW_CROSS="1" \
    PATH="/usr/local/cargo/bin:$PATH" \
    LIBCLANG_PATH="/usr/lib/llvm-10/lib" \
    CC_arm_unknown_linux_musleabihf="arm-linux-musleabihf-gcc" \
    CXX_arm_unknown_linux_musleabihf="arm-linux-musleabihf-g++" \
    AR_arm_unknown_linux_musleabihf="arm-linux-musleabihf-ar" \
    BINDGEN_EXTRA_CLANG_ARGS_arm_unknown_linux_musleabihf="--sysroot=/usr/arm-linux-musleabihf" \
    PKG_CONFIG_PATH_arm_unknown_linux_musleabihf="/usr/arm-linux-musleabihf/lib/pkgconfig" \
    CMAKE_arm_unknown_linux_musleabihf="/opt/cmake/bin/cmake"

COPY setup/lib.sh setup/rustup.sh setup/rubygems.sh setup/cmake.sh setup/rubybashrc.sh setup/rb-sys-dock.sh setup/delete-unused-files.sh /

RUN bash -c "source /lib.sh && install_packages libclang-dev clang llvm-dev" && \
    /rustup.sh && \
    /rubygems.sh && \
    /cmake.sh && \
    /rubybashrc.sh && \
    /delete-unused-files.sh && \
    /rb-sys-dock.sh
