[package]
name = "rust-reverse"
version = "0.9.4"
autotests = false # set true if you want to use "cargo test"

[dependencies]
rb-sys = { path = "./../../../../crates/rb-sys" }
rb-allocator = { path = "./../../../../crates/rb-allocator" }

[lib]
crate-type = ["cdylib"]

[features]
test-feature = []
