[package]
name = "rust-reverse"
version = "0.1.0"
autotests = false # set true if you want to use "cargo test"
autodocs = false

[dependencies]
rb-sys = { path = "./../../../../crates/rb-sys" }
rb-allocator = { path = "./../../../../crates/rb-allocator" }

[lib]
crate-type = ["cdylib"]

[features]
test-feature = []
