[package]
name = "rust-reverse"
version = "0.9.32"
autotests = false # set true if you want to use "cargo test"
edition = "2018"

[dependencies]
rb-sys = { version = "0.9.32", path = "./../../../../crates/rb-sys", features = ["gem", "global-allocator"] }

[lib]
crate-type = ["cdylib"]

[features]
test-feature = []
