[tasks.install]
dependencies = ["build"]
script_runner = "@duckscript"
script = '''
exit_on_error true

libs = glob_array ./target/*/librust_ruby_example.*

function strip_lib_prefix
  echo Stripping lib prefix: ${1}
  new_filename = replace ${1} librust_ruby_example rust_ruby_example
  cp ${1} ${new_filename}
end

for lib in ${libs}
  if ends_with ${lib} .dylib
    strip_lib_prefix ${lib}
  end

  if ends_with ${lib} .so
    strip_lib_prefix ${lib}
  end
end

dylibs = glob_array ./target/*/rust_ruby_example.dylib

for lib in ${dylibs}
  echo Stripping lib suffix: ${lib}
  new_filename = replace ${lib} .dylib .bundle
  cp ${lib} ${new_filename}
  rm ${lib}
end
'''

[tasks.verify]
dependencies = ["install"]
script_runner = "@duckscript"
script = '''
exit_on_error true

libs = glob_array ./target/*/rust_ruby_example.*

for lib in ${libs}
  folder = dirname ${lib}
  exec --fail-on-error ruby -r ./${folder}/rust_ruby_example -e "RustRubyExample.reverse('hello world') == 'dlrow olleh' ? puts('Success!!!') :  abort('Failure')"
end
'''
