[package]
build = "build/main.rs"
name = "rb-sys"
version = "0.9.13"
edition = "2018"
readme = "readme.md"
categories = ["external-ffi-bindings"]
description = "Rust bindings for the CRuby API"
documentation = "https://docs.rs/rb-sys"
homepage = "https://github.com/oxidize-rb/rb-sys"
license = "MIT OR Apache-2.0"
links = "rb"
repository = "https://github.com/oxidize-rb/rb-sys"

[build-dependencies]
bindgen = { version = "0.60", default-features = false, features = ["runtime"] }
linkify = "0.8"
rb-sys-build = { path = "../rb-sys-build", version = "0.9.13" }
cc = { version = "1.0", optional = true }
shell-words = { version = "1.1", optional = true }

[features]
default = []
gem = ["ruby-abi-version"]
link-ruby = []
no-link-ruby = []
ruby-macros = ["cc", "shell-words"]
ruby-static = []
ruby-abi-version = []
global-allocator = []
bindgen-rbimpls = []
bindgen-deprecated-types = []
debug-build = []

[lib]
doctest = false
