[package]
build = "build/main.rs"
name = "rb-sys"
version = "0.9.6"
edition = "2018"
readme = "readme.md"
categories = ["ruby", "external-ffi-bindings"]
description = "Rust bindings for the CRuby API"
documentation = "https://docs.rs/rb-sys"
homepage = "https://github.com/oxidize-rb/rb-sys"
license = "MIT OR Apache-2.0"
links = "rb"
repository = "https://github.com/oxidize-rb/rb-sys"

[build-dependencies]
bindgen = "0.60"
linkify = "0.8"
regex = "1"
rb-sys-build = { path = "../rb-sys-build", version = "0.9.5" }

[build-dependencies.cc]
optional = true
version = "1.0"

[build-dependencies.shell-words]
optional = true
version = "1.1.0"

[dependencies]
libc = "0.2.126"

[features]
default = ["ruby-macros"]
link-ruby = []
ruby-macros = ["cc", "shell-words"]
ruby-static = ["link-ruby"]
include-rbimpls = []
include-deprecated = []

[lib]
doctest = false
