[package]
build = "build/main.rs"
name = "rb-sys"
version = "0.9.54"
edition = "2018"
readme = "readme.md"
categories = ["external-ffi-bindings"]
description = "Rust bindings for the CRuby API"
documentation = "https://docs.rs/rb-sys"
homepage = "https://github.com/oxidize-rb/rb-sys"
license = "MIT OR Apache-2.0"
links = "rb"
repository = "https://github.com/oxidize-rb/rb-sys"

[build-dependencies]
rb-sys-build = { version = "0.9.54", path = "../rb-sys-build" }

[features]
default = []
cc = ["rb-sys-build/cc"]
link-ruby = []
no-link-ruby = []
ruby-macros = ["cc"]
ruby-static = []
global-allocator = []
bindgen-rbimpls = ["rb-sys-build/bindgen-rbimpls"]
bindgen-deprecated-types = ["rb-sys-build/bindgen-deprecated-types"]
bindgen-layout-tests = ["rb-sys-build/bindgen-layout-tests"]

[lib]
doctest = false
