[package]
name = "rb-sys"
version = "0.8.0"
edition = "2018"
links = "ruby"
readme = "readme.md"
categories = ["ruby", "external-ffi-bindings"]

[features]
default = []
ruby-static = []
link-ruby = []

[dependencies]
libc = "0.2.112"

[lib]
doctest = false

[build-dependencies]
bindgen = "0.59"
pkg-config = "0.3.24"
