name: Cache Clean

on:
  pull_request:
    types:
      - closed

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Delete caches
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
              key: context.ref,
            })

            for (const cache of caches.data.actions_caches) {
              console.log(`Deleting cache ${cache.id}`)

              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }

            console.log("Clear completed")
