---
name: Build and push docker images

on:
  workflow_dispatch:
  push:
    tags: [v*]
    paths:
      - "docker/**"
      - ".github/workflows/docker.yml"
      - "rakelib/docker.rake"
      - "gem/exe/rb-sys-dock"

jobs:
  docker_images:
    runs-on: ubuntu-latest
    env:
      RBSYS_DOCKER: "docker buildx"
      RBSYS_DOCKER_BUILD_EXTRA_ARGS: "--cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,mode=max,dest=/tmp/.buildx-cache-new --load"
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ruby_target: x86_64-linux
          - ruby_target: x86_64-linux-musl
          - ruby_target: aarch64-linux
          - ruby_target: arm-linux
          - ruby_target: x86_64-darwin
          - ruby_target: arm64-darwin
          - ruby_target: x64-mingw32
          - ruby_target: x64-mingw-ucrt
          # - ruby_target: x86-mingw32
          # - ruby_target: x86-linux
    steps:
      - uses: actions/checkout@v3

      # Test the container
      - uses: actions/checkout@v3
        with:
          repository: "oxidize-rb/oxi-test"
          path: "tmp/oxi-test"

      - name: Print env info
        run: |
          env

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ matrix.platform.ruby_target }}-buildx-v4-${{ github.sha }}
          restore-keys: |
            ${{ matrix.platform.ruby_target }}-buildx-v4

      - name: Build images
        run: rake docker:build:${{ matrix.platform.ruby_target }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Run tests
        run: |
          sudo chmod 777 tmp/oxi-test
          cd tmp/oxi-test
          gem install rb_sys

          export RB_SYS_DOCK_UID=$(id -u)
          export RB_SYS_DOCK_GID=$(id -g)

          # Soft fail for now
          rb-sys-dock --platform ${{ matrix.platform.ruby_target }} --latest -- \
            "bundle install && bundle exec rake native:${{ matrix.platform.ruby_target }} gem || true"

      - name: Push images
        if: startsWith(github.ref, 'refs/tags/v')
        run: rake docker:push:${{ matrix.platform.ruby_target }}
