---
name: Integration
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.repo.slug }} (ruby=${{ matrix.ruby }}, os=${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        repo:
          - name: "oxidize-rb/oxi-test"
            slug: oxi-test
            ref: main
            run: rake
          - name: "matsadler/magnus"
            slug: magnus
            ref: main
            run: cargo test
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        rust: ["stable", "1.51"]
        ruby: ["2.7", "3.0", "3.1", "3.2", "head"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Log matrix
        shell: bash
        env:
          INPUTS: ${{ toJSON(matrix) }}
        run: |
          echo "$INPUTS" | jq
      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo.name }}
          ref: ${{ matrix.repo.ref }}
      - uses: actions/checkout@v3
        with:
          path: /tmp/rb-sys
      - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        id: setup
        with:
          ruby-version: ${{ matrix.ruby }}
          rustup-toolchain: ${{ matrix.rust }}
          cache-version: v1-${{ matrix.repo.slug }}
          cargo-cache: true
          cargo-cache-clean: true
      - name: ✏️ Replace rb-sys
        shell: bash
        run: |
          mkdir -p .cargo
          echo "[patch.crates-io]" >> .cargo/config
          echo "rb-sys = { path = \"/tmp/rb-sys/crates/rb-sys\" }" >> .cargo/config
          cargo update -p rb-sys
          cd /tmp/rb-sys/gem

          # Replace rb-sys in gemspec
          echo "RUBYOPT=-I/tmp/rb-sys/gem/lib" >> $GITHUB_ENV
          ruby -e "File.write('Gemfile', File.read('Gemfile').gsub(/gem .rb_sys.*$/, 'gem \"rb_sys\", path: \"/tmp/rb-sys/gem\"'))" || true
          bundle install -j3 --retry 3 || true
      - name: 🧪 Run tests for ${{ matrix.repo.slug }}
        shell: bash
        run: ${{ matrix.repo.run }}
